import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Category } from 'src/app/products/product.model';

@Injectable({
  providedIn: 'root',
})
export class DatabaseService implements InMemoryDbService {
  constructor() {}
  createDb() {
    return {
      users: [
        {
          id: 1,
          email: 'vaib@gmail.com',
          password: 'password11',
          name: 'Vaibhav',
          role: 'Admin',
        },
        {
          id: 2,
          email: 'vaib1@gmail.com',
          password: 'password22',
          name: 'John Smith',
          role: 'User',
        },
        {
          id: 3,
          email: 'vaib2@gmail.com',
          password: 'password22',
          name: 'James Cook',
          role: 'User',
        },
      ],
      products: [
        {
          id: 1,
          name: 'Lettuce',
          price: '40',
          category: Category.veges,
          rating: 4,
          image: '../../assets/images/lettuce.png',
          description: 'This is a tomato',
        },
        {
          id: 2,
          name: 'Spinach',
          price: '140',
          category: Category.veges,
          rating: 4.5,
          image: 'assets/images/spinach.png',
          description: 'These are delicious corn',
        },
        {
          id: 3,
          name: 'Silverbeet',
          price: '30',
          category: Category.veges,
          rating: 4,
          image: '../../assets/images/silverbeet.png',
          description: 'This is a tomato',
        },
        {
          id: 4,
          name: 'Cabbage',
          price: '45',
          category: Category.veges,
          rating: 4.5,
          image: 'assets/images/cabbage.png',
          description: 'These are delicious corn',
        },
        {
          id: 5,
          name: 'Cauliflower',
          price: '60',
          category: Category.veges,
          rating: 4,
          image: '../../assets/images/cauliflower.png',
          description: 'This is a tomato',
        },
        {
          id: 6,
          name: 'Brussels Sprouts',
          price: '140',
          category: Category.veges,
          rating: 4.5,
          image: 'assets/images/brussels.png',
          description: 'These are delicious corn',
        },
        {
          id: 7,
          name: 'Broccoli',
          price: '50',
          category: Category.veges,
          rating: 4,
          image: '../../assets/images/broccoli.png',
          description: 'This is a tomato',
        },
        {
          id: 8,
          name: 'Pumpkin',
          price: '10',
          category: Category.veges,
          rating: 4.5,
          image: 'assets/images/pumpkin.png',
          description: 'These are delicious corn',
        },
        {
          id: 60,
          name: 'Phone',
          price: '40000',
          category: Category.electronics,
          rating: 5,
          image: '../assets/images/RsmartPhone1.jpg',
          description: 'This is a smart Phone',
        },
        {
          id: 61,
          name: 'Phone',
          price: '40000',
          category: Category.electronics,
          rating: 5,
          image: '../assets/images/RsmartPhone1.jpg',
          description: 'This is a smart Phone',
        },
        {
          id: 62,
          name: 'Phone',
          price: '40000',
          category: Category.electronics,
          rating: 5,
          image: '../assets/images/RsmartPhone1.jpg',
          description: 'This is a smart Phone',
        },
        {
          id: 63,
          name: 'Phone',
          price: '40000',
          category: Category.electronics,
          rating: 5,
          image: '../assets/images/RsmartPhone1.jpg',
          description: 'This is a smart Phone',
        },
        {
          id: 64,
          name: 'Phone',
          price: '40000',
          category: Category.electronics,
          rating: 5,
          image: '../assets/images/RsmartPhone1.jpg',
          description: 'This is a smart Phone',
        },
        {
          id: 65,
          name: 'Phone',
          price: '40000',
          category: Category.electronics,
          rating: 5,
          image: '../assets/images/RsmartPhone1.jpg',
          description: 'This is a smart Phone',
        },
        {
          id: 80,
          name: 'Apples',
          price: '200',
          category: Category.fruits,
          rating: 5,
          image: '../assets/images/apple.png',
          description: 'These are apples',
        },
        {
          id: 81,
          name: 'Pears',
          price: '100',
          category: Category.fruits,
          rating: 4,
          image: '../assets/images/pear.png',
          description: 'This is a pear',
        },
        {
          id: 82,
          name: 'Oranges',
          price: '60',
          category: Category.fruits,
          rating: 3.5,
          image: '../assets/images/orange.png',
          description: 'These are oranges',
        },
        {
          id: 83,
          name: 'Grapefruits',
          price: '90',
          category: Category.fruits,
          rating: 3,
          image: '../assets/images/grapefruit.png',
          description: 'These are grapes',
        },
        {
          id: 84,
          name: 'Apricots',
          price: '120',
          category: Category.fruits,
          rating: 2.5,
          image: '../assets/images/apricot.png',
          description: 'This is an Apricot',
        },
        {
          id: 85,
          name: 'Strawberries',
          price: '420',
          category: Category.fruits,
          rating: 1,
          image: '../assets/images/strawberry.png',
          description: 'These are strawberries',
        },
      ],
    };
  }
}
